site_name: Atlas Docs
site_description: A fast, AI-powered, fully offline voice assistant.
site_author: Minkx1
site_url: https://minkx1.github.io/Atlas/
repo_name: Minkx1/Atlas
repo_url: https://github.com/Minkx1/Atlas

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    scheme: slate 
    primary: indigo
    accent: light blue

nav:
  - Home: index.md
  - Installation: installation.md
  - Architecture: architecture.md
  - Plugin API: plugins.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html